### ISSUE TITLE
Is this a bug?  \237 in an email name

### ISSUE THREAD

**Issue by ddssff** [peti/hsemail#2]
import Text.Parsec (parse)
    import Text.ParserCombinators.Parsec.Rfc2822 (address)

    main = do
      parse address "" "Dav\237d Fox <nobody@nowhere>"

Output:

    Left (line 1, column 9):
    unexpected "\237"
    expecting word, ".", white-space, carriage return followed by linefeed, comment or ":"

The character is "Unicode Character 'LATIN SMALL LETTER I WITH ACUTE' (U+00ED)"

**Comment by peti** [comment]
E-mail headers are restricted to a subset of 7-bit ASCII characters. Any character outside of that range must be encoded according to https://tools.ietf.org/html/rfc2047, so that recipient knows what kind of character set and encoding was used.

**Comment by ddssff** [comment]
Ah, thank you.
