### ISSUE TITLE
Why are some cases handled differently?

### ISSUE THREAD

**Issue by ad-si** [peti/hsemail#7]
I'm trying to understand the sourcecode, and I stumbled upon this:

```haskell
day_name :: Stream s m Char => ParsecT s u m DayOfWeek
day_name = choice [ caseString "Mon" $> Monday
                  , try (caseString "Tue" $> Tuesday)
                  , caseString "Wed" $> Wednesday
                  , caseString "Thu" $> Thursday
                  , caseString "Fri" $> Friday
                  , try (caseString "Sat" $> Saturday)
                  , caseString "Sun" $> Sunday
                  ]
           <?> "name of a day-of-the-week"
```

Why do *only* Tue and Sat have an extra `try` call and what is it good for?

**Comment by peti** [comment]
When the parser for "Tue" encounters the input "Thu" it consumes the "T" and then fails. This means that the entire `choice` fails: by default, Parsec will not backtrack and try the other parsers. Without the `try` wrapper to enable backtracking, "Thu" would never parse successfully. See https://hackage.haskell.org/package/parsec-3.1.17.0/docs/Text-Parsec.html#v:try for further details.
